const mimeTypes = {
    html: 'text/html',
    htm: 'text/html',
    mht: 'multipart/related',
    gif: 'image/gif',
    png: 'image/png',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    bmp: 'image/bmp',
    doc: 'application/msword',
    docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    docm: 'application/vnd.ms-word.document.macroEnabled.12',
    rtf: 'application/rtf',
    txt: 'text/plain',
    wps: 'application/vnd.ms-works',
    xml: 'application/xml',
    odt: 'application/vnd.oasis.opendocument.text',
    ott: 'application/vnd.oasis.opendocument.text-template',
    wpd: 'application/wordperfect',
    ps: 'application/postscript',
    infopathxml: 'application/xml',
    xls: 'application/vnd.ms-excel',
    xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    xlsm: 'application/vnd.ms-excel.sheet.macroEnabled.12',
    xlsb: 'application/vnd.ms-excel.sheet.binary.macroEnabled.12',
    csv: 'text/csv',
    dif: 'application/vnd.ms-excel',
    ods: 'application/vnd.oasis.opendocument.spreadsheet',
    ots: 'application/vnd.oasis.opendocument.spreadsheet-template',
    ppt: 'application/vnd.ms-powerpoint',
    pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    pptm: 'application/vnd.ms-powerpoint.presentation.macroEnabled.12',
    odp: 'application/vnd.oasis.opendocument.presentation',
    otp: 'application/vnd.oasis.opendocument.presentation-template',
    pps: 'application/vnd.ms-powerpoint',
    ppsx: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
    ppsm: 'application/vnd.ms-powerpoint.slideshow.macroEnabled.12',
    vsd: 'application/vnd.visio',
    vdx: 'application/vnd.visio',
    svg: 'image/svg+xml',
    svgz: 'image/svg+xml',
    vdw: 'application/vnd.visio',
    dxf: 'image/vnd.dxf',
    dwg: 'image/vnd.dwg',
    tif: 'image/tiff',
    tiff: 'image/tiff',
    msg: 'application/vnd.ms-outlook',
    eml: 'message/rfc822',
    pdf: 'application/pdf',
    vsdx: 'application/vnd.visio',
    vss: 'application/vnd.visio',
    vssx: 'application/vnd.visio',
    vst: 'application/vnd.visio',
    vstx: 'application/vnd.visio',
    xlt: 'application/vnd.ms-excel',
    xltx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
    dot: 'application/msword',
    dotx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
    xfdf: 'application/vnd.adobe.xfdf',
    dgn: 'application/x-dgn',
    fdf: 'application/vnd.fdf'
  };
module.exports = {
    getMime: (ext) => {
      return mimeTypes[ext.toLowerCase()] || 'application/octet-stream';
    },  
}